logging:
  config: classpath:logback/logback-dev.xml

spring:
  datasource:
   type: org.apache.tomcat.jdbc.pool.DataSource
   driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
   url: jdbc:log4jdbc:postgresql://localhost:8080/test
   username: localhost
   password: localhost!
   dbcp2:
     test-on-borrow: true
     validation-query: SELECT NOW();  
  devtools: 
   livereload: 
    enable: true
  freemarker:
   cache: false
  
server:
  port: 10024