logging:
  config: classpath:logback/logback.xml 
  
spring:
  datasource:
   type: org.apache.tomcat.jdbc.pool.DataSource
   driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
   url: jdbc:log4jdbc:postgresql://192.168.33.81:5432/oprdb
   username: pzdev
   password: 1q2w3e4r%T
   dbcp2:
     test-on-borrow: true
     validation-query: SELECT NOW();  
  devtools: 
   livereload: 
    enable: true
  freemarker:
   cache: false
  
iot:
  serverIp: 192.168.33.81
  serverPort: 10050
  externalSysId: OPEN_TCP
  deviceId: WEATHER
  password: 1234
  helathCheckuseYn: false
  
weather:
#  api_key: HhpkLRVEoyTgB%2F5UIy3DpvpcHQ1Tvr2v4FC2aIQGPO4eEmZFB6KM8ryw9fTKwXKaQ9drLgm6KUIHbYzD6Z%2B0Lw%3D%3D
  pos_x: 62
  pos_y: 123
  
server:
  port: 10024
  
apikey: RGAPI-3c046478-2929-4c7e-a9e9-1efa19b2c7bb